obiad_project/obiad/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'obiad'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    
    path('obiad_choice/', login_required(views.meal_choice), name='obiad_choice'),
    path('kucharz_dashboard/', views.kucharz_dashboard, name='kucharz_dashboard'),
    
]

obiad_project/obiad_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('obiad.urls', 'obiad'), namespace='obiad')),
]

obiad_project/obiad/models.py
from django.db import models
from django.contrib.auth.models import User

class MealChoice(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    data = models.DateField(unique=True,default=None)
    sniadanie = models.BooleanField(default=False)
    obiad = models.BooleanField(default=False)
    kolacja = models.BooleanField(default=False)

    def __str__(self):
        return f"Posiłek {self.data} dla {self.user}"

obiad_project/obiad/forms.py
from django import forms
from .models import MealChoice
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Podaj swoje imię.')
    surname = forms.CharField(max_length=30, required=True, help_text='Podaj swoje nazwisko.')

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'surname')






class MealChoiceForm(forms.ModelForm):
    class Meta:
        model = MealChoice
        fields = ['data', 'sniadanie', 'obiad', 'kolacja']
    def __init__(self, *args, **kwargs):
        super(MealChoiceForm, self).__init__(*args, **kwargs)
        self.fields['sniadanie'].widget.attrs['class'] = 'meal-checkbox'
        self.fields['obiad'].widget.attrs['class'] = 'meal-checkbox'
        self.fields['kolacja'].widget.attrs['class'] = 'meal-checkbox'

obiad_project/obiad/views.py
from multiprocessing import AuthenticationError
from django.http import HttpResponseRedirect
from .models import MealChoice
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth import authenticate, login
from .forms import MealChoiceForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
import locale
from django.contrib.auth.decorators import user_passes_test

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('obiad:user_login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'obiad/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('obiad:obiad_choice')
        else:
            messages.error(request, 'Nieprawidłowa nazwa użytkownika lub hasło.', extra_tags='login_error')
    return render(request, 'obiad/user_login.html')



def index(request):
    return render(request, 'obiad/index.html')



import datetime
@login_required
def meal_choice(request):
    now = datetime.datetime.now()
    start_date = now.date()
    


    if now.time() > datetime.time(8, 0):
        # Jeśli jest po godzinie 8, dodaj jeden dzień do daty początkowej
        start_date += datetime.timedelta(days=1)

    dates = [start_date + datetime.timedelta(days=i) for i in range(14)]
    #user_choices = MealChoice.objects.filter(user=request.user, data__in=dates)
    #print(user_choices)
    if request.method == 'POST':
        form = MealChoiceForm(request.POST)
        if form.is_valid():
            meal_choice = form.save(commit=False)
            meal_choice.user = request.user
            meal_choice.save()
            success_message = "Wybory zostały zapisane pomyślnie."
            return redirect('obiad:obiad_choice')
    else:
        form = MealChoiceForm()
    
    return render(request, 'obiad/obiad_choice.html', {'form': form, 'dates': dates})
'''
def meal_choice(request):
    user = request.user
    
    try:
        meal_choice = MealChoice.objects.get(user=user)
    except MealChoice.DoesNotExist:
        meal_choice = None

    now = datetime.datetime.now()
    current_time = now.time()

    next_choice_date = now.date()

    # Ograniczenia czasowe dla wszystkich dni tygodnia
    if current_time > datetime.time(8, 0):
        next_choice_date += datetime.timedelta(days=1)

    all_days = [(next_choice_date + datetime.timedelta(days=i)).strftime('%Y-%m-%d %A') for i in range(14)]

    if request.method == 'POST':
        form = MealChoiceForm(request.POST, instance=meal_choice)
        if form.is_valid():
            if meal_choice is None:
                meal_choice = form.save(commit=False)
                meal_choice.user = user

            for day in all_days:
                want_obiad_key = 'want_obiad_' + day
                want_sniadanie_key = 'want_sniadanie_' + day
                want_kolacja_key = 'want_kolacja_' + day
                meal_choice.want_obiad = request.POST.get(want_obiad_key) == 'on'
                meal_choice.want_sniadanie = request.POST.get(want_sniadanie_key) == 'on'
                meal_choice.want_kolacja = request.POST.get(want_kolacja_key) == 'on'

            meal_choice.last_choice_date = next_choice_date
            meal_choice.save()
            return redirect('obiad:obiad_choice')
    else:
        if meal_choice is None:
            meal_choice = MealChoice(user=user)
        form = MealChoiceForm(instance=meal_choice)

    wybory_uzytkownika = {
        'want_obiad': meal_choice.want_obiad,
        'want_sniadanie': meal_choice.want_sniadanie,
        'want_kolacja': meal_choice.want_kolacja,
    }

    return render(request, 'obiad/obiad_choice.html', {'obiad_choice': meal_choice, 'form': form, 'next_choice_date': next_choice_date, 'all_days': all_days})
'''
@user_passes_test(lambda user: user.groups.filter(name='kucharz').exists())
def kucharz_dashboard(request):
    meal_choices = MealChoice.objects.all()  # Pobierz wszystkie wybory posiłków

    context = {
        'meal_choices': meal_choices,
    }

    return render(request, 'obiad/kucharz_dashboard.html', context)

from django.http import HttpResponse

obiad_project/obiad/templates/obiad/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Wybór obiadu</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <img src="https://th.bing.com/th/id/OIP.go-3SeXNJ76Vao7QjFbyXgHaEo?pid=ImgDet&rs=1" alt="Obrazek" />
        <h2>Wybierz opcję:</h2>
        <a class="btn" href="{% url 'obiad:register' %}">Zarejestruj się</a>
        <a class="btn" href="{% url 'obiad:user_login' %}">Zaloguj się</a>
    </div>
</body>
</html>

obiad_project/obiad/templates/obiad/kucharz_dashboard.html
<!DOCTYPE html>
<html lang="pl">
<head>    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ilość osób</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <h2>Dashboard kucharza</h2>
        <table>
            <thead>
                <tr>
                    <th>Data</th>
                    <th>Śniadanie</th>
                    <th>Obiad</th>
                    <th>Kolacja</th>
                </tr>
            </thead>
            <tbody>
                {% for choice in meal_choices %}
                <tr>
                    <td>{{ choice.date }}</td>
                    <td>{{ choice.num_want_sniadanie }}</td>
                    <td>{{ choice.num_want_obiad }}</td>
                    <td>{{ choice.num_want_kolacja }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>
    

obiad_project/obiad/templates/obiad/obiad_choice.html
<!DOCTYPE html>
<html lang="pl">
<head>    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rezerwacja posiłków</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>


<body>

    <div class="container">
        <h2>Wybór posiłków</h2>
        <h2>Wybierz posiłki na najbliższe 2 tygodnie</h2>
        {% if success_message %}
        <div class="success-message">{{ success_message }}</div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <table>
                <thead>
                    <tr>
                        <th>Data</th>
                        <th>Śniadanie</th>
                        <th>Obiad</th>
                        <th>Kolacja</th>
                    </tr>
                </thead>
                <tbody>
                    {% for date in dates %}
                    <tr>
                        <td>{{ date }}</td>
                        <td><input type="checkbox" class="meal-checkbox" name="sniadanie_{{ date }}" /></td>
                        <td><input type="checkbox" class="meal-checkbox" name="obiad_{{ date }}" /></td>
                        <td><input type="checkbox" class="meal-checkbox" name="kolacja_{{ date }}" /></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <button type="submit">Zapisz</button>
        </form>

        {% if user_choices %}
        <h2>Twoje aktualne wybory:</h2>
        <table>
            <thead>
                <tr>
                    <th>Data</th>
                    <th>Śniadanie</th>
                    <th>Obiad</th>
                    <th>Kolacja</th>
                </tr>
            </thead>
            <tbody>
                {% for choice in user_choices %}
                <tr>
                    <td>{{ choice.data }}</td>
                    <td>{% if choice.sniadanie %}Tak{% else %}Nie{% endif %}</td>
                    <td>{% if choice.obiad %}Tak{% else %}Nie{% endif %}</td>
                    <td>{% if choice.kolacja %}Tak{% else %}Nie{% endif %}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}

        <a class="btn" href="{% url 'obiad:kucharz_dashboard' %}">Panel kucharza</a>
        <p><a class="btn" href="{% url 'obiad:index' %}">Powrót do strony głównej</a></p>
    </div>


</body>
</html>

obiad_project/obiad/templates/obiad/register.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rejestracja</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <h2>Rejestracja</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn" type="submit">Zarejestruj się</button>
        </form>
        <p><a class="btn" href="{% url 'obiad:user_login' %}">Do strony logowania</a></p>
        <p><a class="btn" href="{% url 'obiad:index' %}">Powrót do strony głównej</a></p>
    </div>
</body>
</html>

obiad_project/obiad/templates/obiad/user_login.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logowanie</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
        <h2>Logowanie</h2>
        <form method="post">
            {% csrf_token %}
            <label for="username">Nazwa użytkownika:</label>
            <input type="text" name="username" required>
            <br>
            <label for="password">Hasło:</label>
            <input type="password" name="password" required>
            <br>
            <button type="submit">Zaloguj się</button>
        </form>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% if messages %}
            <div class="success-message">
                {% for message in messages %}
                    {% if message.tags == 'success' and message.extra_tags == 'registration_success' %}
                        {{ message }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <!-- Wyświetlanie błędu -->
        {% if messages %}
            <div class="error-message">
                {% for message in messages %}
                    {% if message.tags == 'error' and message.extra_tags == 'login_error' %}
                        {{ message }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        
        <p>Nie masz jeszcze konta? <a class="btn" href="{% url 'obiad:register' %}">Zarejestruj się</a></p>
        <p><a class="btn" href="{% url 'obiad:index' %}">Powrót do strony głównej</a></p>
    </div>
</body>
</html>